"""Byte-stable schema assertion.

Locks the JSON serialization of a known registry tree so that any change to
the schema format is caught immediately. Anyone changing the schema shape
must update the golden string deliberately.
"""
import json

from src.variable_tools import Registry


def _build_golden_registry() -> Registry:
    r = Registry("golden")
    ctrl = r.add_child("controller")
    pid = ctrl.add_child("pid")
    pid.add_double("kp", 5.0, tunable=True, min=0.0, max=100.0, units="N/rad")
    pid.add_double("ki", 0.1, tunable=True, min=0.0)
    ctrl.add_enum("state", "idle", ["idle", "moving", "fault"], tunable=True)
    diag = r.add_child("diagnostics")
    diag.add_int("loop_count", 0)
    diag.add_bool("fault_active", False)
    diag.add_double("loop_time_ms", 0.0, units="ms")
    return r


# Stored golden. Generated by:
#   json.dumps(_build_golden_registry().schema(), sort_keys=True)
# If you intentionally change the schema format, run that snippet and paste
# the new string here.
GOLDEN = (
    '{"children": ['
    '{"children": ['
    '{"children": [], "name": "pid", "variables": ['
    '{"max": 100.0, "min": 0.0, "name": "kp", "tunable": true, "type": "double", "units": "N/rad"}, '
    '{"min": 0.0, "name": "ki", "tunable": true, "type": "double"}'
    '], "version": 2}'
    '], '
    '"name": "controller", '
    '"variables": ['
    '{"cases": ["idle", "moving", "fault"], "name": "state", "tunable": true, "type": "enum"}'
    '], "version": 2}, '
    '{"children": [], "name": "diagnostics", "variables": ['
    '{"name": "loop_count", "tunable": false, "type": "integer"}, '
    '{"name": "fault_active", "tunable": false, "type": "boolean"}, '
    '{"name": "loop_time_ms", "tunable": false, "type": "double", "units": "ms"}'
    '], "version": 3}'
    '], '
    '"name": "golden", '
    '"variables": [], '
    '"version": 3}'
)


def test_schema_golden_bytes():
    r = _build_golden_registry()
    serialized = json.dumps(r.schema(), sort_keys=True)
    assert serialized == GOLDEN, (
        "Schema shape changed. If intentional, update GOLDEN to the new value:\n"
        + serialized
    )
